#!/usr/bin/env python

import numpy
import geometry_msgs.msg
import rospy
from sensor_msgs.msg import JointState
import tf
import tf.msg
from urdf_parser_py.urdf import URDF

"""This function will transform a 4x4 transformation matrix T into a ros message 
which can be published. In addition to the transform itself, the message
also specifies who is related by this transform, the parent and the child.
It is an optional function which you may use as you see fit."""
def convert_to_message(T, child, parent):
    t = geometry_msgs.msg.TransformStamped()
    t.header.frame_id = parent
    t.header.stamp = rospy.Time.now()
    t.child_frame_id = child
    translation = tf.transformations.translation_from_matrix(T)
    rotation = tf.transformations.quaternion_from_matrix(T)
    t.transform.translation.x = translation[0]
    t.transform.translation.y = translation[1]
    t.transform.translation.z = translation[2]
    t.transform.rotation.x = rotation[0]
    t.transform.rotation.y = rotation[1]
    t.transform.rotation.z = rotation[2]
    t.transform.rotation.w = rotation[3]        
    return t
    
#Our main class for computing Forward Kinematics
class ForwardKinematics(object):

    #Initialization
    def __init__(self):
        """Announces that it will publish forward kinematics results, in the form of tfMessages.
        "tf" stands for "transform library", it's ROS's way of communicating around information
        about where things are in the world"""
        self.pub_tf = rospy.Publisher("/tf", tf.msg.tfMessage, queue_size=1)

        #Loads the robot model, which contains the robot's kinematics information
        self.robot = URDF.from_parameter_server()

        #Subscribes to information about what the current joint values are.
        rospy.Subscriber("joint_states", JointState, self.callback)


    """This function is called every time the robot publishes its joint values. You must use
    the information you get to compute forward kinematics.

    The callback you write should iterate through the entire robot chain, and publish 
    the transform for each link you find.
    """
    def callback(self, joint_values):
	# YOUR CODE GOES HERE
	root_link = self.robot.get_root()
	transform_message_array = []
	transform_message_arrayelement = []
	transform= tf.transformations.identity_matrix()
	current_link = root_link
	T = tf.transformations.identity_matrix()
	for i in range(0,len(self.robot.joint_map)):

		(next_jointName, next_link) = self.robot.child_map[current_link][0]
		next_joint = self.robot.joint_map[next_jointName]
		

		info = next_joint.origin
		translation = tf.transformations.translation_matrix(info.xyz)
		rotation = tf.transformations.euler_matrix(info.rpy[0], info.rpy[1], info.rpy[2])
		link_matrix = numpy.dot(translation,rotation)




		if next_joint.type == 'fixed':

			joint_rotation_matrix = tf.transformations.identity_matrix()
			
						
		else:
			
			ind = joint_values.name.index(next_joint.name)
			joint_rotation_quaternion = tf.transformations.quaternion_about_axis(joint_values.position[ind] ,next_joint.axis)
			joint_rotation_matrix = tf.transformations.quaternion_matrix(joint_rotation_quaternion)
			
			
		transformation_matrix_array = numpy.dot(link_matrix,joint_rotation_matrix)

		T = numpy.dot(T, transformation_matrix_array)	

		transform_message_arrayelement = convert_to_message(T,next_link,root_link)
		transform_message_array = numpy.append(transform_message_array,transform_message_arrayelement)
		current_link = next_link		
		
	self.pub_tf.publish(transform_message_array)
		
	transform_messege_array = []	
	
	
	#print(next_joint.origin)
	
if __name__ == '__main__':
    rospy.init_node('fwk', anonymous=True)
    fwk = ForwardKinematics()
    rospy.spin()
